const screenNames = {
	SPLASH_SCREEN: 'SPLASH_SCREEN',
	HOME_SCREEN: 'HOME_SCREEN',
	PROFILE_SCREEN: 'PROFILE_SCREEN',
	HOME_STACK: 'HOME_STACK',
	PROFILE_STACK: 'PROFILE_STACK',
	BOTTOM_TAB_STACK: 'BOTTOM_TAB_STACK',
	LOGIN_SCREEN: 'LOGIN_SCREEN',
};

export default screenNames;
